const NODE_VERSION = parseInt(process.version.trim().replace(/^[=v]+/, ''))

const MIDDY_ELT_ENABLE_ENV_VAR_NAME = 'MIDDY_ELT_ENABLE'
const MIDDY_ELT_HANDLER_ENV_VAR_NAME = 'MIDDY_ELT_HANDLER'
const MIDDY_ELT_TIMEOUT_MARGIN_ENV_VAR_NAME = 'MIDDY_ELT_TIMEOUT_MARGIN'

const MIDDY_ELT_TIMEOUT_MARGIN_DEFAULT_VALUE = 500

const MIDDY_ELT_ENABLED =
    (process.env[MIDDY_ELT_ENABLE_ENV_VAR_NAME] || 'true') === 'true'

module.exports = {
    NODE_VERSION,

    MIDDY_ELT_ENABLE_ENV_VAR_NAME,
    MIDDY_ELT_HANDLER_ENV_VAR_NAME,
    MIDDY_ELT_TIMEOUT_MARGIN_ENV_VAR_NAME,

    MIDDY_ELT_TIMEOUT_MARGIN_DEFAULT_VALUE,

    MIDDY_ELT_ENABLED,
}
